### ISSUE TITLE
Annotating an alias type breaks it

### ISSUE THREAD

**Issue by boynton** [ardielle/ardielle-go#56]
This works:

      type MyBase Struct { String message; }                                                                                        
      type MySubtype1 MyBase;                                                                                                       

But if the subtype has extended annotations added to it:
      type MySubtype2 MyBase (x_y);

Then the result of parsing is:
 
{
    "type": "___forward_reference___",
    "name": "MySubtype2"
}

which is a state that should never leak out.

**Comment by havetisyan** [comment]
Hi @boynton 

looks like #57 commit has some unintended behavior changes for our entity data type. It created a new type called Entity_T2 instead of keeping my Struct as the data type and furthermore, the generated Entity_T2 data type is just an empty class.

type Entity Struct {
    EntityName name; //name of the entity object
    Struct value; //value of the entity
}

The generated java model is:

public class Entity_T2 {
}

public class Entity {
    public String name;
    public Entity_T2 value;
...
}

**Comment by boynton** [comment]
Ok, let me revisit it with a test for that case.

**Comment by boynton** [comment]
Fixed as of revision b12a02b.
